### ISSUE TITLE
--verticalInterpolate should be independently configurable and remove templateVariable

### ISSUE THREAD

**Issue by heikoklein** [metno/fimex#19]
verticalInterpolation to a new set of i.e. atmospheric_sigma_hybrid pressure variables needs as configuration the `ap`, `b` and `hybrid` variables. Currently, these variables need to be added to the input-stream together with a templateVariable rather than to the verticalInterpolation configuration. This leads to some problems, since these configuration needs to get transported through the complete processing chain.

If `--extract.selectVariables` is used, the templateVariable needs to be extracted, too.
If `--interpolate` is used, the templateVariable, even if just a dummy, will be processed

The templateVariable for the vertical-interpolation will also be written to the output-file, though it is just a dummy.

Ideally, only the ap, b and hybrid variables should be needed and given directly to vertical-interpolation (i.e. by a `--verticalInterpolation.ncml=file.ncml`). The templateVariable is not necessary, only the vertical axes are needed. The horizontal axes of the templateVariable are not needed, but are difficult to figure out for vertticalInterpolation. There, I think it would be best if the templateVariable could be dropped and be replace by a vertical-coordinate-axis (i.e. `hybrid`).

**Comment by alexander-buerger-met-no** [comment]
Why not add the variable with ncml, as in the test case `testVerticalInterpolatorSigmaHybridFromPressure.sh`?

**Comment by heikoklein** [comment]
I started from that case. The template-variable is still in the output, the template-variable is still interpolated and lost under extraction unless taken care of. `ap`,`b` and `hybrid` only belong to verticalInterpolation, not anywhere else.

And I need to know the names of the horizontal axes - for verticalInterpolation?

I would like to move my verticalInterpolation setup from one processing-chain to another without interfering with the rest of the setup unless absolutely needed (i.e. surface_pressure not found)

**Comment by alexander-buerger-met-no** [comment]
The template variable is used to obtain a `VerticalTransformation` from the template variable's `CoordinateSystem`. At present, only `CoordinateSystem` instances are owners of vertical transformations. There is not necessarily any variable with the desired final coordinate system -- actually it is rather unlikely that there is any other variable with the desired coordinate system before vertical interpolation.

As a workaround until this is changed, you could wrap the vertical interpolation step into a python script, adding the ncml before vertical interpolation and removing the template (and whatever else) after interpolation and **before** writing.

You can also use inline xml for the ncml instead of a filename if you want to compose the ncml in python or if you want to reduce the number of files.

**Comment by alexander-buerger-met-no** [comment]
PS: When I wrote "python script," I thought of a python script using the fimex python binding. There it is possible to add a `CDMExtractor`, in this case to remove the template variable, after vertical interpolation.

**Comment by heikoklein** [comment]
In the long run, I would like to see a simplified verticalInterpolate setup which is usable in the Fortran interface. Horizontal interpolation is already there. Using a system outside of fimex does not really help me.

**Comment by alexander-buerger-met-no** [comment]
Should be closed with commit f4723d30.
