### ISSUE TITLE
Feature request: xml-stdout option to the fimex binary

### ISSUE THREAD

**Issue by FrankThomasTveter** [metno/fimex#20]
An option for `fimex` to output data as `XML` to `STDOUT` instead of always writing output data to a file, would be very useful in an operational environment where `fimex` was used to interpolate model data to a limited set of latlon locations. 

This would save on cloud `IO`, shell startup overhead and code complexity handling parallell processes. :-)

**Comment by alexander-buerger-met-no** [comment]
fimex output is typically NetCDF, any generic xml output would need to have similar structure and complexity. I do not think that adding such an output format is worth the effort.

If your use case has a "simple" output, you could use the fimex python binding. After doing all the operations needed, you would end up with a numpy array, which you could print to stdout in the format you like, or pass to some other python function.

**Comment by heikoklein** [comment]
I agree that using the python binding might be much more useful in web-server setup, since it would even further reduce the need to start the fimex process and the output possibilities of python are much more flexible.

On the other hand, NcML is a well-supported xml dialect. fimex can already read XML/NcML with data, and write NcML without data. It should be a simple task to add optional data-writing capabilities to the NcML-output, simplifying manual the modification of some data in ascii format. It should be comparable to 'ncdump' and 'ncdump -v' functionality, i.e. being able to write all data, or only data of some variables. 

This might also be useful for simple web-services for non-python programmers.
